/**
 * Super-spec tests (todo 800) — specs/super-spec.json, generated by
 * scripts/build-super-spec.mjs (npm run spec:build).
 *
 * Covers: build determinism (byte-identical across runs, and the checked-in
 * artifact is current), per-service operation counts, exposure consistency
 * with catalog/manifest.json (ADR-0003: spec paths = manifest operations,
 * every one callable), the judicious skills representation (3 ops + embedded
 * index, NOT one path per skill/section), and the size budget the design doc
 * records (the compact form ships into a sandbox on every search).
 */
import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { EXCLUDED_SCOUT_OPS } from "../scripts/exposure.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_PATH = join(ROOT, "specs", "super-spec.json");

type Operation = {
  operationId: string;
  summary?: string;
  description?: string;
  tags?: string[];
  requestBody?: { content?: Record<string, { schema?: Record<string, unknown> }> };
  responses?: Record<string, { description?: string }>;
  "x-service": string;
  "x-execute"?: string;
  "x-algolia"?: unknown;
  "x-skill-index"?: Array<{ id: string; source: string; description: string; sections: string[] }>;
  "x-runnable-index"?: Array<{
    id: string;
    description: string;
    inputSchema: Record<string, unknown>;
    outputSchema: Record<string, unknown>;
  }>;
};

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as {
  openapi: string;
  info: Record<string, unknown>;
  paths: Record<string, Record<string, Operation>>;
  components: Record<string, Record<string, unknown>>;
  "x-services": Record<string, unknown>;
};

const manifest = JSON.parse(readFileSync(join(ROOT, "catalog", "manifest.json"), "utf8")) as {
  entries: Array<{
    id: string;
    service: string;
    kind: string;
    description: string;
    runnable?: true;
    inputSchema: Record<string, unknown> | null;
    outputSchema: Record<string, unknown> | null;
  }>;
};

function allOps(): Array<[string, string, Operation]> {
  const out: Array<[string, string, Operation]> = [];
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) out.push([path, method, op]);
  }
  return out;
}

describe("build determinism", () => {
  it("the checked-in artifact is current, and two rebuilds are byte-identical", () => {
    const before = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const first = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const second = readFileSync(SPEC_PATH);
    expect(first.equals(second)).toBe(true);
    expect(before.equals(first), "specs/super-spec.json is stale — run npm run spec:build").toBe(
      true
    );
  });
});

describe("shape and counts", () => {
  it("is an OpenAPI-3.1-style doc with the four service tags", () => {
    expect(spec.openapi).toBe("3.1.0");
    expect(Object.keys(spec["x-services"]).sort()).toEqual([
      "lumenloop",
      "scout",
      "skills",
      "stellarDocs"
    ]);
  });

  it("has the expected per-service operation counts (exposed ops only, ADR-0003)", () => {
    const counts: Record<string, number> = {};
    for (const [, , op] of allOps()) {
      counts[op["x-service"]] = (counts[op["x-service"]] ?? 0) + 1;
    }
    // Exactly the manifest operations: excluded ops (paid research, account
    // surface, scout writes) never reach the spec.
    expect(counts.lumenloop).toBe(18);
    expect(counts.scout).toBe(24);
    expect(counts.stellarDocs).toBe(12);
    expect(counts.skills).toBe(4); // list, read, ranked search, run_skill (design §5)
  });

  it("every path is '/{service}/{operation}' and operationIds are unique callable ids", () => {
    const seen = new Set<string>();
    for (const [path, , op] of allOps()) {
      expect(path.startsWith(`/${op["x-service"]}/`), path).toBe(true);
      expect(seen.has(op.operationId), `duplicate ${op.operationId}`).toBe(false);
      seen.add(op.operationId);
      expect(op.tags?.[0]).toBe(op["x-service"]);
    }
  });

  it("every op carries an exact x-execute call line (everything in the spec is callable)", () => {
    for (const [, , op] of allOps()) {
      expect(op["x-execute"], op.operationId).toBeTruthy();
    }
    // Service ops are called as `await <operationId>(args)`.
    for (const [, , op] of allOps()) {
      if (op["x-service"] !== "skills") {
        expect(op["x-execute"]).toBe(`await ${op.operationId}(args)`);
      }
    }
  });

  it("describes search scores on the shared cross-tier interleave scale", () => {
    const search = spec.paths["/skills/search_skills"]!.post!;
    const description = search.responses?.["200"]?.description ?? "";
    expect(description).toContain("Scores share one scale");
    expect(description).toContain(">=1.6x");
    expect(description).toContain("hit order is authoritative");
    expect(description).not.toMatch(/always ranked below every gated hit/i);
    expect(description).not.toMatch(/only among same-tier/i);
    expect(search.summary).toBe("Ranked lexical search over whole skills.");
    expect(search.description).toContain("sections remain readable");
    expect(search.description).toContain("not independent ranked hits");
    expect(search["x-execute"]).toBe(
      'await codemode.search({ query, kind: "skill", service: "skills" })'
    );
  });
});

describe("consistency with the catalog (single source of truth)", () => {
  it("every cataloged operation id appears as an operationId (spec = manifest)", () => {
    const byOperationId = new Map(allOps().map(([, , op]) => [op.operationId, op]));
    const catalogOps = manifest.entries.filter((e) => e.kind === "operation");
    expect(catalogOps.length).toBe(18 + 24 + 12);
    for (const entry of catalogOps) {
      expect(
        byOperationId.get(entry.id),
        `catalog op ${entry.id} missing from super spec`
      ).toBeDefined();
    }
    // …and the reverse: no service op in the spec lacks a manifest entry.
    const manifestIds = new Set(catalogOps.map((e) => e.id));
    for (const [, , op] of allOps()) {
      if (op["x-service"] === "skills") continue; // synthetic core service
      expect(manifestIds.has(op.operationId), `spec-only op ${op.operationId}`).toBe(true);
    }
  });

  it("leaks no excluded endpoint and leaves no dangling component ref (ADR-0003)", () => {
    // The spec is serialized into the sandbox and returned by codemode.spec(),
    // so it is emitted text. Components are copied wholesale from upstream, so
    // a schema describing only an EXCLUDED operation rode along and carried
    // that endpoint's prose with it: scout.FeedbackRequest — the request body
    // of the excluded POST /api/feedback — shipped the raw path this way.
    // build-super-spec.mjs now prunes unreachable components and guards the
    // emitted text.
    // Derived from the exclusion data, never a hand-copied list — a fourth
    // exclusion must tighten this test automatically (house rule, same as
    // test/demo-page.test.ts).
    const serialized = JSON.stringify(spec);
    const excludedPaths = [...EXCLUDED_SCOUT_OPS].map((op) => op.split(" ")[1]!);
    expect(excludedPaths.length).toBeGreaterThan(0);
    for (const path of excludedPaths) {
      expect(serialized.includes(path), `super-spec emits excluded endpoint ${path}`).toBe(false);
    }
    const components = (spec as unknown as { components?: Record<string, Record<string, unknown>> })
      .components ?? {};
    expect(components.schemas?.["scout.FeedbackRequest"]).toBeUndefined();

    // The dangerous direction is the OPPOSITE of the leak: pruning too much.
    // A dropped-but-still-referenced component resolves to `undefined` at
    // runtime (src/executor/spec-sandbox.ts) and vanishes on serialization, so
    // the model would silently receive a degraded contract instead of an error.
    // Verify by RESOLUTION, deliberately not by re-running the build's own
    // reachability walk — a copy of that walk would share any bug it has.
    const dangling: string[] = [];
    const walk = (node: unknown, path: string): void => {
      if (!node || typeof node !== "object") return;
      if (Array.isArray(node)) {
        node.forEach((item, i) => walk(item, `${path}/${i}`));
        return;
      }
      for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
        if (typeof value === "string") {
          const match = value.match(/^#\/components\/([^/]+)\/([^/]+)/);
          if (match) {
            const group = match[1]!;
            const name = match[2]!.replace(/~1/g, "/").replace(/~0/g, "~");
            if (!components[group]?.[name]) dangling.push(`${path}/${key} -> ${value}`);
          }
        } else {
          walk(value, `${path}/${key}`);
        }
      }
    };
    walk(spec, "");
    expect(dangling, "component refs that no longer resolve — the build pruned something live").toEqual([]);
  });

  it("the skills index matches the catalog's exposed (allowed) skills and its section slugs resolve", () => {
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    // Exposure-aware: the index advertises exactly the cataloged skills — the
    // 7 retired Lumenloop onboarding skills have no manifest entry (ADR-0003)
    // and must not appear here.
    const catalogSkillIds = manifest.entries
      .filter((e) => e.service === "skills" && e.kind === "skill")
      .map((e) => e.id)
      .sort();
    expect(index.map((s) => s.id)).toEqual(catalogSkillIds);

    // Heading-list-only index: every listed section corresponds to a cataloged
    // skill-section entry (file:… keys verbatim; headings via the shared slug).
    const sectionIds = new Set(
      manifest.entries.filter((e) => e.kind === "skill-section").map((e) => e.id)
    );
    const slugify = (text: string) =>
      text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "") || "section";
    let checked = 0;
    for (const skill of index) {
      const used = new Set<string>();
      for (const section of skill.sections) {
        let key: string;
        if (section.startsWith("file:")) {
          key = section;
        } else {
          let slug = slugify(section);
          for (let n = 2; used.has(slug); n++) slug = `${slugify(section)}-${n}`;
          used.add(slug);
          key = slug;
        }
        expect(sectionIds.has(`${skill.id}#${key}`), `${skill.id}#${key}`).toBe(true);
        checked += 1;
      }
    }
    expect(checked).toBe(sectionIds.size); // every cataloged section is discoverable in the index
  });

  it("read_skill's name enum is exactly the exposed skill ids", () => {
    const schema = spec.paths["/skills/read_skill"]!.post!.requestBody!.content![
      "application/json"
    ]!.schema as { properties: { name: { enum: string[] } } };
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    expect(schema.properties.name.enum).toEqual(index.map((s) => s.id));
  });
});

describe("runnable skills — /skills/run_skill (design §5)", () => {
  const runSkillOp = () => spec.paths["/skills/run_skill"]!.post!;

  it("exists with the exact dispatch line under the skills service", () => {
    const op = runSkillOp();
    expect(op).toBeDefined();
    expect(op.operationId).toBe("skills.run_skill");
    expect(op["x-service"]).toBe("skills");
    expect(op["x-execute"]).toBe("await codemode.skill.run(name, input)");
  });

  it("name enum is exactly the manifest's runnable skill ids, in manifest (id-sorted) order", () => {
    const schema = runSkillOp().requestBody!.content!["application/json"]!.schema as {
      additionalProperties: boolean;
      required: string[];
      properties: { name: { enum: string[] } };
    };
    const runnableIds = manifest.entries.filter((e) => e.runnable === true).map((e) => e.id);
    expect(runnableIds.length).toBeGreaterThan(0);
    expect(schema.properties.name.enum).toEqual(runnableIds);
    expect(schema.required).toEqual(["name", "input"]);
    expect(schema.additionalProperties).toBe(false);
  });

  it("x-runnable-index matches the manifest entries byte-for-byte (id, description, both schemas)", () => {
    const index = runSkillOp()["x-runnable-index"]!;
    const runnable = manifest.entries.filter((e) => e.runnable === true);
    expect(index.map((s) => s.id)).toEqual(runnable.map((e) => e.id));
    for (const item of index) {
      const entry = runnable.find((e) => e.id === item.id)!;
      expect(item.description).toBe(entry.description);
      // Both artifacts are sortKeysDeep'd by their builders, so JSON string
      // equality is byte equality — the assertRunnersWired pinning, checked
      // across the two emitted surfaces.
      expect(JSON.stringify(item.inputSchema), item.id).toBe(JSON.stringify(entry.inputSchema));
      expect(JSON.stringify(item.outputSchema), item.id).toBe(JSON.stringify(entry.outputSchema));
    }
  });
});

describe("service specifics", () => {
  it("stellarDocs ops keep the algolia mapping as a vendor extension", () => {
    const docsOps = allOps().filter(([, , op]) => op["x-service"] === "stellarDocs");
    for (const [, , op] of docsOps) {
      expect(op["x-algolia"], op.operationId).toBeDefined();
    }
    const backend = (spec["x-services"].stellarDocs as { backend: { type: string } }).backend;
    expect(backend.type).toBe("algolia");
  });

  it("scout $refs resolve within the merged doc (namespaced components)", () => {
    const refs = JSON.stringify(spec.paths).match(/"\$ref":"([^"]+)"/g) ?? [];
    expect(refs.length).toBeGreaterThan(0);
    for (const raw of refs) {
      const ref = raw.slice('"$ref":"'.length, -1);
      expect(ref.startsWith("#/components/"), ref).toBe(true);
      const [, , group, name] = ref.split("/");
      expect(
        (spec.components[group!] as Record<string, unknown>)[name!],
        `unresolvable ${ref}`
      ).toBeDefined();
    }
  });

  it("lumenloop tool descriptions carry when_to_use/returns; excluded ops have no path", () => {
    const searchDirectory = spec.paths["/lumenloop/search_directory"]!.post!;
    expect(searchDirectory.description).toContain("When to use:");
    expect(searchDirectory.description).toContain("Returns:");
    // The paid research trigger and the account surface are build-time
    // excluded (ADR-0003) — they do not exist in the spec at all.
    expect(spec.paths["/lumenloop/request_research"]).toBeUndefined();
    expect(JSON.stringify(Object.keys(spec.paths))).not.toContain("webhook");
  });
});

describe("size budget (design doc §4)", () => {
  it("the compact form that ships into each search sandbox stays under 300 KB", () => {
    const compact = Buffer.byteLength(JSON.stringify(spec), "utf8");
    expect(compact).toBeLessThan(300 * 1024);
  });
});
