/**
 * Small JSON-Schema argument validator — args are validated against the
 * entry's `inputSchema` BEFORE any network call (ARCHITECTURE.md: model code never
 * owns endpoints/args).
 *
 * Why hand-rolled and not zod-from-JSON-Schema: zod v4 converts zod→JSON
 * Schema, not the reverse; a conversion dependency would be another moving
 * part for a *bounded* dialect. The manifest's input schemas are generated by
 * our own builder and use exactly these keywords (measured over all 374
 * entries): type, properties, required, additionalProperties, enum, minimum,
 * maximum, minLength, maxLength, minItems, maxItems, pattern, items, format,
 * default, description. ~120 lines cover the whole dialect with precise,
 * model-actionable messages; unknown keywords are deliberately ignored
 * (validation is a guard, not a conformance suite).
 */

export type ValidationIssue = { path: string; message: string };

type Schema = {
  type?: string | string[];
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  enum?: unknown[];
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  items?: Schema;
  [k: string]: unknown;
};

function typeOf(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "array";
  return typeof value;
}

function matchesType(value: unknown, type: string): boolean {
  const t = typeOf(value);
  if (type === "integer") return t === "number" && Number.isInteger(value);
  if (type === "number") return t === "number";
  return t === type;
}

function validateValue(value: unknown, schema: Schema, path: string, issues: ValidationIssue[]): void {
  if (schema.type !== undefined) {
    const types = Array.isArray(schema.type) ? schema.type : [schema.type];
    if (!types.some((t) => matchesType(value, t))) {
      issues.push({ path, message: `expected ${types.join(" | ")}, got ${typeOf(value)}` });
      return; // further keyword checks would only cascade noise
    }
  }

  if (schema.enum !== undefined && !schema.enum.some((v) => v === value)) {
    issues.push({
      path,
      message: `must be one of: ${schema.enum.map((v) => JSON.stringify(v)).join(", ")}`
    });
  }

  if (typeof value === "number") {
    if (schema.minimum !== undefined && value < schema.minimum) {
      issues.push({ path, message: `must be >= ${schema.minimum}` });
    }
    if (schema.maximum !== undefined && value > schema.maximum) {
      issues.push({ path, message: `must be <= ${schema.maximum}` });
    }
  }

  if (typeof value === "string") {
    if (schema.minLength !== undefined && value.length < schema.minLength) {
      issues.push({ path, message: `must be at least ${schema.minLength} characters` });
    }
    if (schema.maxLength !== undefined && value.length > schema.maxLength) {
      issues.push({ path, message: `must be at most ${schema.maxLength} characters` });
    }
    if (schema.pattern !== undefined) {
      let re: RegExp | null = null;
      try {
        re = new RegExp(schema.pattern);
      } catch {
        /* unparseable pattern in the manifest: skip, builder bug not model bug */
      }
      if (re && !re.test(value)) {
        issues.push({ path, message: `must match pattern ${schema.pattern}` });
      }
    }
  }

  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) {
      issues.push({ path, message: `must have at least ${schema.minItems} items` });
    }
    if (schema.maxItems !== undefined && value.length > schema.maxItems) {
      issues.push({ path, message: `must have at most ${schema.maxItems} items` });
    }
    if (schema.items) {
      value.forEach((item, i) => validateValue(item, schema.items as Schema, `${path}[${i}]`, issues));
    }
  }

  if (typeOf(value) === "object") {
    validateObject(value as Record<string, unknown>, schema, path, issues);
  }
}

function validateObject(
  obj: Record<string, unknown>,
  schema: Schema,
  path: string,
  issues: ValidationIssue[]
): void {
  const props = schema.properties ?? {};
  for (const name of schema.required ?? []) {
    if (obj[name] === undefined) {
      issues.push({ path: path ? `${path}.${name}` : name, message: "required" });
    }
  }
  for (const [name, value] of Object.entries(obj)) {
    if (value === undefined) continue;
    const childPath = path ? `${path}.${name}` : name;
    const propSchema = props[name];
    if (propSchema) {
      validateValue(value, propSchema, childPath, issues);
    } else if (schema.additionalProperties === false) {
      issues.push({
        path: childPath,
        message: `unknown argument (allowed: ${Object.keys(props).join(", ") || "none"})`
      });
    }
  }
}

/**
 * Validate call args against a manifest input schema.
 * Returns [] when valid; otherwise a list of {path, message} issues the
 * model can act on directly.
 */
export function validateArgs(
  schema: Record<string, unknown> | null,
  args: unknown
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  if (args !== undefined && typeOf(args) !== "object") {
    return [{ path: "", message: `arguments must be a single object, got ${typeOf(args)}` }];
  }
  const obj = (args ?? {}) as Record<string, unknown>;
  if (!schema) {
    // No declared schema: only an object-shaped arg is enforced (above).
    return issues;
  }
  validateObject(obj, schema as Schema, "", issues);
  return issues;
}
